version: 2.1

orbs:
  node: circleci/node@4.7
  coveralls: coveralls/coveralls@1.0.6

workflows:
  test-lint:
    jobs:
      - node/test
      - node/run:
          npm-run: lint
      - coverage:
        executor: node/default
        steps:
          - checkout
          - node/install-packages
          - run: npm run coverage
          - coveralls/upload
